css infoscience
epfl-si/infoscience-exports pull request #59
Opened 2018-03-16 15:04 UTC by dragonleman

2018-03-16 19:41 UTC, ebreton requested changes
Hello... alors j'ai du louper un truc... j'ai l'impression qu'on revient en arrière sur la rétro-compatibilité et les modifications des ELA_URL...

je te laisse regarder les commentaires. (je ne les ai pas répétés sur chaque ligne)

2018-03-16 19:41 UTC, ebreton commented on infoscience_exports/exports/templates/exports/export_detailed.html
> +		<h1>{{ groups.title }}</h1>
la classe `infoscience_header1` devrait être conservée pour garder la compatiblité avec le HTML produit par le système précédent

exemple dans https://infoscience-legacy.epfl.ch/curator/export/11497/?ln=en

2018-03-16 19:41 UTC, ebreton commented on infoscience_exports/exports/templates/base/base.html
> +<body class="infoscience_publication_exports search">
la classe parente dans l'ancien système semble être un `<div class="infoscience_export">`

c.f https://test-infoscience.epfl.ch/curator/export/12572/

2018-03-16 19:41 UTC, ebreton commented on infoscience_exports/exports/templates/exports/export_detailed.html
> +			<h2>{{ article.title }}</h2>
idem, la classe `infoscience_header2` devrait être conservée à mon avis

2018-03-16 19:41 UTC, ebreton commented on infoscience_exports/exports/templates/exports/export_detailed.html
> +							{% trans "Full text" %}: {{ article.ELA_URL }}
pourquoi on zappe le .0 ici ?

2018-03-16 19:41 UTC, ebreton commented on infoscience_exports/exports/templates/exports/export_detailed.html
> +							{% if options.link_detailed %} - {% endif %}<a class="infoscience_link_fulltext" href="{{ article.ELA_URL }}" target="_blank">{% trans "Full text" %}</a>
idem... `.0` ?

2018-03-16 21:20 UTC, dragonleman commented on infoscience_exports/exports/templates/exports/export_detailed.html
> +							{% trans "Full text" %}: {{ article.ELA_URL }}
J'avais mal compris ton dernier commit sur les ".0". J'avais cru que tu les avais supprimés. Effectivement, tu les avais ajoutés et cela a un sens, puisque les ELA_URL sont une liste à la base. Je corrigerai lundi.

2018-03-16 21:27 UTC, dragonleman commented on infoscience_exports/exports/templates/exports/export_detailed.html
> +			<h2>{{ article.title }}</h2>
La meilleure chose à faire serait de supprimer la branche. Je vais la refaire, et au vu des peu de modifications (et en plus toutes à revoir) , c'est bien simple ainsi.

2018-03-17 08:01 UTC, ebreton commented on infoscience_exports/exports/templates/exports/export_detailed.html
> +			<h2>{{ article.title }}</h2>
ok, ça me va aussi, le plus simple pour toi.

Dans ce cas, tu peux fermer la PR sans la merger !

++
Manu

2018-03-18 00:07 UTC, closed without merging