Refactored set fulltexts
epfl-si/infoscience-exports pull request #62
Opened 2018-03-17 20:57 UTC by ebreton

Hello @dragonleman ,

Je suis repassé sur set_fulltext pour la rendre plus pythonesque, et ajouter des tests unitaires qui explicitent le comportement (il y a des pdf, pdfa, et aussi ppt et asp...)

En revanche, j'ai vu que tu ne l'appelais plus nulle part dans le code ... ?

on avait avant ```dict_result['ELA_URL'] = set_fulltext(fulltexts)```, mais il a sauté au commit https://github.com/epfl-idevelop/infoscience-exports/commit/8377ea42c375aebf19292bfd1060a74ba8ad4f8b

normal ?

2018-03-17 23:42 UTC, dragonleman commented
Je me demande comment l'appel à la fonction set_fulltext ait pu disparaître ainsi. La fonction doit être appelée :

==============================
# get dictionary (icon, fulltexts) of ELA
def get_ELA_fields(field):
    ela_fulltexts = []
    ela_icon = ''
    for ela in field:
         ELA_type = ela.get('x', '').lower()
         if ELA_type == 'icon':
             ela_icon = ela.get('u', '')
         elif ELA_type == 'public':
             ela_fulltexts.append(ela.get('u', ''))
    ela_fulltexts = list(filter(None, ela_fulltexts))
    **ela_fulltexts = set_fulltext(ela_fulltexts)**
    return {'icon': ela_icon, 'fulltexts': ela_fulltexts} 
==============================
C'est la raison pour laquelle j'avais mal interprété tes ".0" à chaque appel à article.ELA_URL dans les templates: je pensais que tu les avais supprimés, pas ajoutés ...

2018-03-18 00:06 UTC, dragonleman requested changes
Seulement l'appel à get_fulltext. Et, à vérifier, tous les appels dans les templates à ELA_URL, où il faudra enlever les ".0".

2018-03-18 08:58 UTC, ebreton commented
Aucune idée de comment ça a disparut... 😯 

Mais en tout cas, la ligne n'était pas là dans le commit qui a ajouté la fonction (https://github.com/epfl-idevelop/infoscience-exports/commit/8377ea42c375aebf19292bfd1060a74ba8ad4f8b#diff-75a2b8ce6d351c48326a1234d952edc4R112), et il n'y a eu ensuite qu'un modif (flake8) qui ne l'a ni ajoutée ni enlevée 😬 

peut-être juste une mauvaise manip. Mais ce n'est pas vraiment important maintenant qu'on a identifié le soucis ☺️ 

En tout cas c'est mieux sans les `.0` que j'ai rajoutés partout... c'était pas très propre

Je vais pousser le code qui rajoute l'appel à set fulltext et faire marche arrière sur les `.0`

2018-03-18 09:02 UTC, ebreton commented
voilà, @dragonleman je te laisse me dire si on est bon comme ça :)

2018-03-18 19:32 UTC, dragonleman approved these changes

2018-03-18 20:11 UTC, merged