activated defailed forms + added summary
epfl-si/infoscience-exports pull request #78
Opened 2018-03-21 16:58 UTC by dragonleman

2018-03-21 19:27 UTC, ebreton requested changes
voila qui conclue les nouvelles demandes 🥇 

Il y a juste les tests à ajuster pour que le build travis passe, et tout bon.

2018-03-22 08:06 UTC, dragonleman commented
Voilà. Tests ok. J'attends ton @ebreton retour.

2018-03-22 08:17 UTC, ebreton commented
Génial ! Merci 🌟

2018-03-22 08:18 UTC, ebreton approved these changes

2018-03-22 09:05 UTC, merged