Add a 15 min db cache for reading exports
epfl-si/infoscience-exports pull request #81
Opened 2018-03-23 10:24 UTC by jdelasoie

Attention, il faut commenter le DummyCache si vous voulez voir le changement en dév ou en test.

https://github.com/epfl-idevelop/infoscience-exports/blob/07c88c2e05a1f73e80438797283a262dd21a3651/infoscience_exports/settings/test.py#L30

2018-03-23 15:10 UTC, ebreton requested changes
ça va faire du bien :)

si tu peux juste passer le délai de cache dans une variable d'environnment, ça sera plus facile de changer.

On pourrait d'ailleurs mettre 1seconde pour la dev, histoire d'avoir le cache sans les effets secondaires...

2018-03-23 15:10 UTC, ebreton commented on infoscience_exports/exports/urls.py
> +    url(r'^(?P<pk>\d+)/$', cache_page(60*15)(views.ExportView.as_view()), name='export-view'),
ça serait mieux en variables de settings, qui vient elle-même d'une variable d'environnement

2018-03-23 15:10 UTC, ebreton commented on infoscience_exports/settings/base.py
> +        'TIMEOUT': None, # persistant, at least until MAX_ENTRIES
c'est bizarre de mettre une valeur None ici alors qu'on mets 15 minutes plus haut, non ?

2018-03-23 17:22 UTC, ebreton commented
Autre demande 😇 : peux-tu indiquer dans la description de la PR ce que TIND devra effectuer pour cette PR en plus de la commande migrate (qu'ils ont automatisée)

par exemple la création du nouveau schema, la déclaration de la variable d'environnement...

2018-03-26 10:26 UTC, jdelasoie commented
Deleted because of the merged https://github.com/epfl-idevelop/infoscience-exports/pull/82

2018-03-26 10:26 UTC, closed without merging